---
# tasks file for swarm-join
- name: Join the swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_hostname }}"
    join_token: "{{ hostvars['swarm-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ swarm-manager ]