all:
  children:
    swarm_master:
      hosts:
        swarm-master:
    swarm_worker:
      hosts:
        swarm-worker:
        
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '/home/jenkins/.ssh/id_rsa'
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'