all:
  children:
    managers:
      hosts:
        swarm-master:
    workers:
      hosts:
        swarm-worker:
        
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: 'home/jenkins/.ssh/id_rsa'
    ansible_python_interpreter: "/usr/bin/python3"